import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Web Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='relative w-full h-full'>
          <div className='absolute inset-0 h-full w-full bg-[linear-gradient(to_right,#d1d1d115_1px,transparent_1px),linear-gradient(to_bottom,#d1d1d115_1px,transparent_1px)] bg-[size:24px_24px] -z-50'></div>
          <div className='w-full max-w-screen-xl mx-auto px-5 min-h-screen flex flex-col font-RobotoSerif'>
            <Navbar/>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
